# lightning.pytorch==2.0.0
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: 'logs/domainnet'
      name: 'real_source'
      version: 'source_model_OPDA'
  log_every_n_steps: 5
  max_epochs: 50  # we used 50 for DomainNet and 10 for VisDA
  min_epochs: null
  check_val_every_n_epoch: 1
  enable_checkpointing: False
model:
  class_path: networks.SourceModule
  init_args:
    feature_dim: 256
    lr: 1e-2  # we used 1e-2 for DomainNet and 1e-3 for VisDA
data:
  class_path: datasets.DomainNetDataModule  # select dataset (use VisDADataModule for VisDA-C)
  init_args:
    batch_size: 64
    category_shift: 'OPDA'  # select category shift scenario
    train_domain: 'real'  # select source domain

